spring:
  datasource:
    url: jdbc:sqlserver://job-server.database.windows.net:1433;database=dbjob;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    username: admintest
    password: JACfsd09
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.SQLServer2012Dialect

server:
  port: 3306